language: node_js
node_js:
  - "5"
  - "4"
  - "0.12"
  - "0.10"
before_install:
  - "npm install -g node-gyp"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
